### ISSUE TITLE
Add `CONTRIBUTING.md` documentation

### ISSUE THREAD

**Issue by d33bs** [numfocus/MOSS#6]
It'd be helpful to add a `CONTRIBUTING.md` file which stipulates how contributions may be made to this repository. Commonly this file includes procedures surrounding how to create issues, changes, pull requests, etc. and who may perform certain duties related to these things. Issue was inspired from discussions surrounding pull request reviews, which could address "human verified / reviewed" statements or desires for the content (when utilizing LLM's for development purposes).

**Comment by eyermt** [comment]
@speco29 made a great starting point for this document, there is still more to add as we identify areas of contribution.
